/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StartProgram */

#ifndef _Included_StartProgram
#define _Included_StartProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StartProgram
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StartProgram_printText
  (JNIEnv *, jobject);

/*
 * Class:     StartProgram
 * Method:    initializeInterruptHandler
 * Signature: (LInterruptHandler;)V
 */
JNIEXPORT void JNICALL Java_StartProgram_initializeInterruptHandler
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
